services:
  checkuser:
    image: "overleafregister_image"
    container_name: checkuser
    hostname: checkuser
    restart: always

    networks:
      - overleaf-network

    volumes:
      - /docker/compose/check_users/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

    entrypoint: >
      /bin/sh -c "pip install argh && cd / && sleep infinity"


networks:
  overleaf-network:
    external: true
