services:
  postgres:
    image: postgres:16
    container_name: keycloakpostgres
    hostname: keycloakpostgres
    volumes:
      - /docker/compose/keycloakpostgres/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak-network

networks:
  keycloak-network:
    external: true

