services:
  overleafnginx:
    image: nginx:stable-alpine
    container_name: overleafnginx
    hostname: overleafnginx
    restart: always
    volumes:
      - "/docker/compose/overleafnginx/key.pem:/certs/nginx_key.pem:ro"
      - "/docker/compose/overleafnginx/ca.pem:/certs/nginx_certificate.pem:ro"
      - "/docker/compose/overleafnginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    environment:
      NGINX_WORKER_PROCESSES: "4"
      NGINX_WORKER_CONNECTIONS: "768"
    networks:
      - overleaf-network
      - keycloak-network

networks:
  overleaf-network:
    external: true
  keycloak-network:
    external: true

