services:
  overleafregister:
    image: "overleafregister_image"
    container_name: overleafregister
    hostname: overleafregister
    restart: always

    networks:
      - overleaf-network
      - keycloak-network

    volumes:
      - /docker/compose/overleafregister/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    
#    entrypoint: ["sh", "-c", "sleep infinity"]

networks:

  keycloak-network:
    external: true

  overleaf-network:
    external: true
